version: '3.9'
services:
  filial_ms:
    build: .
    container_name: app_filial_ms
    ports:
      - "3101:3000"
    environment:
      - USER_ID=filial-ms
    volumes:
      - ./sessions/filial-ms:/app/.wwebjs_auth/session-filial-ms

  filial_mt:
    build: .
    container_name: app_filial_mt
    ports:
      - "3102:3000"
    environment:
      - USER_ID=filial-mt
    volumes:
      - ./sessions/filial-mt:/app/.wwebjs_auth/session-filial-mt

  filial_pr:
    build: .
    container_name: app_filial_pr
    ports:
      - "3103:3000"
    environment:
      - USER_ID=filial-pr
    volumes:
      - ./sessions/filial-pr:/app/.wwebjs_auth/session-filial-pr

  filial_go:
    build: .
    container_name: app_filial_go
    ports:
      - "3104:3000"
    environment:
      - USER_ID=filial-go
    volumes:
      - ./sessions/filial-go:/app/.wwebjs_auth/session-filial-go

  vhf_sp:
    build: .
    container_name: app_vhf_sp
    ports:
      - "3105:3000"
    environment:
      - USER_ID=vhf-sp
    volumes:
      - ./sessions/vhf-sp:/app/.wwebjs_auth/session-vhf-sp

  vans_sp:
    build: .
    container_name: app_vans_sp
    ports:
      - "3106:3000"
    environment:
      - USER_ID=vans-sp
    volumes:
      - ./sessions/vans-sp:/app/.wwebjs_auth/session-vans-sp

  sudeste:
    build: .
    container_name: app_sudeste
    ports:
      - "3107:3000"
    environment:
      - USER_ID=sudeste
    volumes:
      - ./sessions/sudeste:/app/.wwebjs_auth/session-sudeste

  sul:
    build: .
    container_name: app_sul
    ports:
      - "3108:3000"
    environment:
      - USER_ID=sul
    volumes:
      - ./sessions/sul:/app/.wwebjs_auth/session-sul

  mg:
    build: .
    container_name: app_mg
    ports:
      - "3109:3000"
    environment:
      - USER_ID=mg
    volumes:
      - ./sessions/mg:/app/.wwebjs_auth/session-mg

  norte:
    build: .
    container_name: app_norte
    ports:
      - "3110:3000"
    environment:
      - USER_ID=norte
    volumes:
      - ./sessions/norte:/app/.wwebjs_auth/session-norte

  nordeste:
    build: .
    container_name: app_nordeste
    ports:
      - "3111:3000"
    environment:
      - USER_ID=nordeste
    volumes:
      - ./sessions/nordeste:/app/.wwebjs_auth/session-nordeste

  projetos:
    build: .
    container_name: app_projetos
    ports:
      - "3112:3000"
    environment:
      - USER_ID=projetos
    volumes:
      - ./sessions/projetos:/app/.wwebjs_auth/session-projetos

  comex1:
    build: .
    container_name: app_comex1
    ports:
      - "3113:3000"
    environment:
      - USER_ID=comex1
    volumes:
      - ./sessions/comex1:/app/.wwebjs_auth/session-comex1

  comex2:
    build: .
    container_name: app_comex2
    ports:
      - "3114:3000"
    environment:
      - USER_ID=comex2
    volumes:
      - ./sessions/comex2:/app/.wwebjs_auth/session-comex2

  comex3:
    build: .
    container_name: app_comex3
    ports:
      - "3115:3000"
    environment:
      - USER_ID=comex3
    volumes:
      - ./sessions/comex3:/app/.wwebjs_auth/session-comex3