# Dockerfile.api
FROM node:18-slim
WORKDIR /app

# 1) Copia o único package.json da raiz
COPY package*.json ./

# 2) Instala só as deps de produção
RUN npm ci --omit=dev

# 3) Copia o código da API
COPY backend/ ./backend

WORKDIR /app/backend
EXPOSE 3000

CMD ["node", "api.js"]
